New hash (#376)
* Multiple signature: drop unsafe algorithm, and now signature form is (index, Ri, Si, ... , Rj, Sj)

* Fix link error: undefined reference boost::log

* Set new multi-sign valid height is 72000, and backward compatibility

* add new hash

* Update an input of merkle root from prepared transactions to be packaged for hash calculation to generate a new block:
1, blockmaker internal miner;
2, getwork/submitwork from RPC command for external miner;

* change judgement from block version to its height

* reduce log from rollback watching

* make unique judgement threshold for all three features

* resolve conflict of linked dependency to build

* refactor common defines header

* Add tx height to verify signature

* adjust message layout and content feeding to miner

* detach merkle as input

* test code

* update testnet parameter

* Restore height code

* update

* test

* Signature and Verification of multiple keys use the same height: HEIGHT_HASH_MULTI_SIGNER

* Fix compilation error on linux

* set up threshold to 20

* set main net parameter to test

* set formal height of hard fork for main net

* update minor version of bigbang from 1.0.0 to 1.1.0

* adjust height

* update log

Co-authored-by: Hantao Sun <jhkghmn@gmail.com>
Co-authored-by: shang <shang_qd@qq.com>